### ISSUE TITLE
Request for a VB19B version?

### ISSUE THREAD

**Issue by RonBeyers** [CMRR-C2P/Spectroscopy#3]
We've been using your VB19A version of the MEGA-PRESS sequence on  our Siemens Vertio 3T until the scanner got upgraded to VB19B.  Now we're stuck with no MEGA-PRESS unless you can generate a VB19B version?
Sincerely, Ron Beyers, Auburn University

**Comment by eauerbach** [comment]
Please contact me if you are still interested in this.

**Comment by RonBeyers** [comment]
Hi Eddie,

I confirm it’s OK to close the action.  We reverted back to VB19A to avoid the problems with VB19B, so the issue is gone.

Regards,
Ron Beyers, PhD
Magnetic Resonance Physicist and Research Engineer VI

Auburn University MRI Research Center
560 Devall Drive, Suite 202
Auburn University, Alabama 36849-5551

Email: RJB0018@Auburn.edu<mailto:RJB0018@Auburn.edu> or
             Ron.Beyers@Auburn.edu<mailto:Ron.Beyers@Auburn.edu>
Office Ph:  334-844-7568
Mobile Ph: 334-734-1566
Fax Ph:      334-844-0214
