### ISSUE TITLE
pTx on Terra

### ISSUE THREAD

**Issue by ileppe** [CMRR-C2P/Spectroscopy#4]
Hello,
We would like to use the sequences on our Terra in pTx mode (specifically the eja_svs_steam). We have successfully used them on the sTx host but get the following error when we try to run it on the pTx system:
`Pipeline preparation failed: Composer Error in Protocol`
This happens even when I try to run the svs_steam with the default `B1 shimming->TrueForm` or the csi_laser with the same mode. Are there different versions specifically compiled for the pTx?
Thanks a lot!

**Comment by eauerbach** [comment]
Is this VE11U or VE12U? Did you install using the installer script (this error could occur if the ICE program is not installed)?

**Comment by ileppe** [comment]
Indeed, it seemed to have not installed properly the first time! A fresh install with the script fixed the issue. Thanks and sorry about that (it's VE12U).
